package jetbrains.mps.lang.migration.runtime.base;

/*Generated by MPS */

import jetbrains.mps.errors.item.ReportItem;
import jetbrains.mps.errors.item.IssueKindReportItem;
import jetbrains.mps.errors.MessageStatus;
import java.util.Set;
import jetbrains.mps.errors.item.FlavouredItem;
import java.util.Collections;

public abstract class Problem<T> implements ReportItem, IssueKindReportItem {
  private T myReason;

  public Problem(T reason) {
    myReason = reason;
  }

  public abstract String getMessage();

  public abstract String getCategory();

  @Override
  public final String getIssueKind() {
    return getCategory();
  }
  @Override
  public MessageStatus getSeverity() {
    return MessageStatus.ERROR;
  }
  @Override
  public Set<FlavouredItem.ReportItemFlavour<?, ?>> getIdFlavours() {
    return Collections.<FlavouredItem.ReportItemFlavour<?, ?>>singleton(FLAVOUR_CLASS);

  }

  public T getReason() {
    return myReason;
  }
}
