package jetbrains.mps.execution.configurations.implementation.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.part.ApplicationPluginPart;
import java.util.Deque;
import jetbrains.mps.execution.api.configurations.ConfigTypeEnvoy;
import java.util.ArrayDeque;
import java.util.List;
import com.intellij.execution.junit.RuntimeConfigurationProducer;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import com.intellij.openapi.extensions.ExtensionPoint;
import com.intellij.execution.configurations.ConfigurationType;
import com.intellij.openapi.extensions.Extensions;
import com.intellij.icons.AllIcons;
import jetbrains.mps.icons.MPSIcons;
import java.util.Iterator;

public class RunConfigurationsInitializer_AppPluginPart extends ApplicationPluginPart {
  private Deque<ConfigTypeEnvoy> myRegisteredKinds = new ArrayDeque<ConfigTypeEnvoy>();
  private List<RuntimeConfigurationProducer> myRegisteredProducers = ListSequence.fromList(new ArrayList<RuntimeConfigurationProducer>());
  public RunConfigurationsInitializer_AppPluginPart() {
  }
  @Override
  public void init() {
    // register kinds 
    ExtensionPoint<ConfigurationType> configurationExtensionPoint = Extensions.getRootArea().getExtensionPoint(ConfigurationType.CONFIGURATION_TYPE_EP);
    {
      ConfigTypeEnvoy runConfigurationKind = new ConfigTypeEnvoy("Java Application", AllIcons.RunConfigurations.Application, "Java Application", "Java Application");
      runConfigurationKind.addFactory(new Java_Configuration_Factory(runConfigurationKind));
      RunConfigurationsInitializer_AppPluginPart.this.myRegisteredKinds.add(runConfigurationKind);
      configurationExtensionPoint.registerExtension(runConfigurationKind);
    }
    {
      ConfigTypeEnvoy runConfigurationKind = new ConfigTypeEnvoy("JUnit Tests", AllIcons.RunConfigurations.Junit, "JUnit Tests", "JUnit Tests");
      runConfigurationKind.addFactory(new JUnitTests_Configuration_Factory(runConfigurationKind));
      RunConfigurationsInitializer_AppPluginPart.this.myRegisteredKinds.add(runConfigurationKind);
      configurationExtensionPoint.registerExtension(runConfigurationKind);
    }
    {
      ConfigTypeEnvoy runConfigurationKind = new ConfigTypeEnvoy("MPS", MPSIcons.MPS16x16, "MPS", "MPS");
      runConfigurationKind.addFactory(new MPSInstance_Configuration_Factory(runConfigurationKind));
      runConfigurationKind.addFactory(new DeployPlugins_Configuration_Factory(runConfigurationKind));
      RunConfigurationsInitializer_AppPluginPart.this.myRegisteredKinds.add(runConfigurationKind);
      configurationExtensionPoint.registerExtension(runConfigurationKind);
    }
    {
      ConfigTypeEnvoy runConfigurationKind = new ConfigTypeEnvoy("Remote", AllIcons.RunConfigurations.Remote, "Remote", "Remote");
      runConfigurationKind.addFactory(new Remote_Configuration_Factory(runConfigurationKind));
      RunConfigurationsInitializer_AppPluginPart.this.myRegisteredKinds.add(runConfigurationKind);
      configurationExtensionPoint.registerExtension(runConfigurationKind);
    }

    // add foreign factories 

    // register creators 
    ExtensionPoint<RuntimeConfigurationProducer> producerExtensionPoint = Extensions.getArea(null).getExtensionPoint(RuntimeConfigurationProducer.RUNTIME_CONFIGURATION_PRODUCER);
    for (ConfigurationType ext : configurationExtensionPoint.getExtensions()) {
      if ("Java Application".equals(ext.getId())) {
        List<RuntimeConfigurationProducer> configurationProducers = Java_Producer.getProducers(ext);
        ListSequence.fromList(RunConfigurationsInitializer_AppPluginPart.this.myRegisteredProducers).addSequence(ListSequence.fromList(configurationProducers));
        for (RuntimeConfigurationProducer producer : ListSequence.fromList(configurationProducers)) {
          producerExtensionPoint.registerExtension(producer);
        }
        break;
      }
    }
    for (ConfigurationType ext : configurationExtensionPoint.getExtensions()) {
      if ("JUnit Tests".equals(ext.getId())) {
        List<RuntimeConfigurationProducer> configurationProducers = JUnitTests_Producer.getProducers(ext);
        ListSequence.fromList(RunConfigurationsInitializer_AppPluginPart.this.myRegisteredProducers).addSequence(ListSequence.fromList(configurationProducers));
        for (RuntimeConfigurationProducer producer : ListSequence.fromList(configurationProducers)) {
          producerExtensionPoint.registerExtension(producer);
        }
        break;
      }
    }
  }
  @Override
  public void dispose() {
    ExtensionPoint<ConfigurationType> configurationExtensionPoint = Extensions.getRootArea().getExtensionPoint(ConfigurationType.CONFIGURATION_TYPE_EP);
    for (Iterator<ConfigTypeEnvoy> it = RunConfigurationsInitializer_AppPluginPart.this.myRegisteredKinds.descendingIterator(); it.hasNext();) {
      ConfigTypeEnvoy configKind = it.next();
      configKind.invalidate();
      configurationExtensionPoint.unregisterExtension(configKind);
    }
    RunConfigurationsInitializer_AppPluginPart.this.myRegisteredKinds.clear();

    // FIXME why there's no code to unregister 'foreign' configuration factories? 

    ExtensionPoint<RuntimeConfigurationProducer> producerExtensionPoint = Extensions.getRootArea().getExtensionPoint(RuntimeConfigurationProducer.RUNTIME_CONFIGURATION_PRODUCER);
    for (RuntimeConfigurationProducer producer : ListSequence.fromList(RunConfigurationsInitializer_AppPluginPart.this.myRegisteredProducers)) {
      producerExtensionPoint.unregisterExtension(producer);
    }
    ListSequence.fromList(RunConfigurationsInitializer_AppPluginPart.this.myRegisteredProducers).clear();
  }
}
