package jetbrains.mps.lang.plugin.standalone.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a2a0a0b0n = new IconResource("applicationPlugin.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a7b0n = new IconResource("projectPlugin.png", IconContainer.class);
}
