package jetbrains.mps.baseLanguage.unitTest.execution.server;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.unitTest.execution.client.ITestNodeWrapper;
import jetbrains.mps.project.Project;
import jetbrains.mps.classloading.ClassLoaderManager;
import org.junit.runner.Request;
import jetbrains.mps.smodel.ModelAccessHelper;
import jetbrains.mps.util.Computable;
import java.util.List;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.module.SModule;
import org.junit.runner.Description;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.module.ModuleClassLoaderIsNullException;
import jetbrains.mps.module.ReloadableModule;
import jetbrains.mps.classloading.ModuleIsNotLoadableException;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class NodeWrappersTestsContributor implements TestsContributor {
  private final Iterable<? extends ITestNodeWrapper> myTestNodes;
  private final Project myProject;
  private final ClassLoaderManager myClassloaderManager;


  public NodeWrappersTestsContributor(Project mpsProject, Iterable<? extends ITestNodeWrapper> testNodes) {
    myTestNodes = testNodes;
    myProject = mpsProject;
    myClassloaderManager = mpsProject.getComponent(ClassLoaderManager.class);
  }

  @Override
  public Iterable<Request> gatherTests() throws Exception {
    return new ModelAccessHelper(myProject.getModelAccess()).runReadAction(new Computable<List<Request>>() {
      public List<Request> compute() {
        final List<Request> requestList = new ArrayList<Request>();
        InProcessExecutionFilter filter = new InProcessExecutionFilter();
        for (ITestNodeWrapper testNode : myTestNodes) {
          String fqName = testNode.getFqName();
          final SNode tn = testNode.getNode();
          final SModule module = getModuleByNode(tn);
          if (testNode.isTestCase()) {
            Request requestForClass;
            try {
              final Class<?> aClass = loadTestClass(fqName, module);
              requestForClass = filter.prepare(testNode, tn, Request.aClass(aClass));
            } catch (ClassNotFoundException e) {
              requestForClass = Request.runner(new AssumptionFailedRunner(e, Description.createSuiteDescription(fqName)));
            }
            requestList.add(requestForClass);
          } else {
            int index = fqName.lastIndexOf('.');
            String testFqName = fqName.substring(0, index);
            String methodName = fqName.substring(index + 1);
            Request requestForMethod;
            try {
              final Class aClass = loadTestClass(testFqName, module);
              requestForMethod = filter.prepare(testNode, tn, Request.method(aClass, methodName));
            } catch (ClassNotFoundException e) {
              requestForMethod = Request.runner(new AssumptionFailedRunner(e, Description.createTestDescription(testFqName, methodName)));
            }
            requestList.add(requestForMethod);
          }
        }
        return requestList;
      }
    });
  }

  @NotNull
  private Class<?> loadTestClass(String fqName, SModule module) throws ClassNotFoundException, ModuleClassLoaderIsNullException {
    if (module instanceof ReloadableModule && myClassloaderManager.isLoadedByMPS(((ReloadableModule) module))) {
      return ((ReloadableModule) module).getOwnClass(fqName);
    } else {
      throw new ModuleIsNotLoadableException(module, "Module's " + module + " classes are managed by MPS (try setting compileInMPS flag to true)");
    }
  }

  private static SModule getModuleByNode(SNode testNode) {
    final SModel model = SNodeOperations.getModel(testNode);
    return model.getModule();
  }
}
