package jetbrains.mps.lang.modelapi.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {



}
