package jetbrains.mps.samples.customizedDebugger.Bottomline.debug.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import java.util.List;
import jetbrains.mps.plugins.part.ApplicationPluginPart;

public class Debug_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("jetbrains.mps.samples.customizedDebugger.Bottomline.debug");
  public Debug_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  @Override
  public void fillCustomParts(List<ApplicationPluginPart> parts) {
    parts.add(new DebugInfoProvider_AppPluginPart());
  }
}
